# Generated by Django 2.1.5 on 2019-10-26 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='book',
            field=models.ManyToManyField(to='catalog.Book'),
        ),
    ]
