# Generated by Django 2.1.5 on 2019-10-26 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_language_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='language',
            name='book',
        ),
        migrations.AddField(
            model_name='language',
            name='book',
            field=models.ForeignKey(default='Python cook book', on_delete=django.db.models.deletion.CASCADE, to='catalog.Book'),
            preserve_default=False,
        ),
    ]
