# Generated by Django 2.1.5 on 2019-10-26 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20191026_1024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='language',
            name='book',
        ),
        migrations.AddField(
            model_name='language',
            name='book',
            field=models.ManyToManyField(to='catalog.Book'),
        ),
    ]
